-- MIGRACION 007: Sincronizar Supervisores
-- Autor: Antigravity AI
-- Fecha: 2025-12-09
-- Descripción: Actualiza el campo SUPERVISOR_ACTUAL en NEU_CABECERA trayendo el valor de PO_NEUMATICO.USUARIO_SUPER.
-- Esto es necesario porque la migración Clean Start (004) dejaba este campo en NULL.
-- También actualiza el registro inicial en NEU_DETALLE.

-- 1. Actualizar Cabecera
UPDATE SPEED400AT.NEU_CABECERA C
SET C.SUPERVISOR_ACTUAL = (
    SELECT CAST(P.USUARIO_SUPER AS VARCHAR(50))
    FROM SPEED400AT.PO_NEUMATICO P
    WHERE P.CODIGO = C.CODIGO_CASCO
)
WHERE EXISTS (
    SELECT 1 
    FROM SPEED400AT.PO_NEUMATICO P 
    WHERE P.CODIGO = C.CODIGO_CASCO 
    AND P.USUARIO_SUPER IS NOT NULL
);

-- 2. Actualizar Detalle (Solo el registro de MIGRACION inicial)
UPDATE SPEED400AT.NEU_DETALLE D
SET D.SUPERVISOR = (
    SELECT CAST(P.USUARIO_SUPER AS VARCHAR(50))
    FROM SPEED400AT.PO_NEUMATICO P
    WHERE P.CODIGO = D.CODIGO_CASCO
)
WHERE D.TIPO_ACCION = 'INGRESO_INVENTARIO'
AND EXISTS (
    SELECT 1 
    FROM SPEED400AT.PO_NEUMATICO P 
    WHERE P.CODIGO = D.CODIGO_CASCO 
    AND P.USUARIO_SUPER IS NOT NULL
);
