-- MIGRACION 008: Implementar Catálogo de Estados Normalizado
-- Autor: Antigravity AI
-- Fecha: 2025-12-09
-- Descripción: Crea tabla NEU_ESTADO, migra los strings de NEU_CABECERA a IDs, y reemplaza la columna.

-- 1. Crear Tabla de Estados
CREATE TABLE SPEED400AT.NEU_ESTADO (
    ID_ESTADO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_INTERNO VARCHAR(20) NOT NULL, -- Para uso en backend (STOCK, ASIGNADO)
    DESCRIPCION VARCHAR(50) NOT NULL,    -- Para mostrar al usuario (DISPONIBLE, ASIGNADO, BAJA DEFINITIVA)
    COLOR_HEX VARCHAR(10) DEFAULT '#000000'
);

-- 2. Poblar Estados Maestros (Estandarización Estricta)
INSERT INTO SPEED400AT.NEU_ESTADO (CODIGO_INTERNO, DESCRIPCION, COLOR_HEX) VALUES ('DISPONIBLE', 'DISPONIBLE', '#2e7d32');
INSERT INTO SPEED400AT.NEU_ESTADO (CODIGO_INTERNO, DESCRIPCION, COLOR_HEX) VALUES ('ASIGNADO', 'ASIGNADO', '#1976d2');
INSERT INTO SPEED400AT.NEU_ESTADO (CODIGO_INTERNO, DESCRIPCION, COLOR_HEX) VALUES ('BAJA', 'BAJA DEFINITIVA', '#d32f2f');
INSERT INTO SPEED400AT.NEU_ESTADO (CODIGO_INTERNO, DESCRIPCION, COLOR_HEX) VALUES ('RECUPERADO', 'RECUPERADO', '#ed6c02');

-- 3. Modificar Tabla Cabecera
-- Agregamos la columna ID_ESTADO
ALTER TABLE SPEED400AT.NEU_CABECERA ADD COLUMN ID_ESTADO INT;

-- 4. Migrar Datos Existentes
-- Mapeamos el string actual al nuevo ID (STOCK antigua -> DISPONIBLE nueva)
UPDATE SPEED400AT.NEU_CABECERA C
SET C.ID_ESTADO = (
  SELECT E.ID_ESTADO FROM SPEED400AT.NEU_ESTADO E 
  WHERE E.CODIGO_INTERNO = CASE WHEN C.ESTADO_ACTUAL = 'STOCK' THEN 'DISPONIBLE' ELSE C.ESTADO_ACTUAL END
);

-- NOTA: Si hay alguno nulo o no coincidente, lo forzamos a DISPONIBLE
UPDATE SPEED400AT.NEU_CABECERA
SET ID_ESTADO = (SELECT ID_ESTADO FROM SPEED400AT.NEU_ESTADO WHERE CODIGO_INTERNO = 'DISPONIBLE')
WHERE ID_ESTADO IS NULL;

-- 5. Establecer FK (Opcional, pero recomendado para integridad)
ALTER TABLE SPEED400AT.NEU_CABECERA 
ADD CONSTRAINT FK_NEU_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES SPEED400AT.NEU_ESTADO(ID_ESTADO);

-- ============================================================================
-- 6. ACTUALIZACION DE DETALLE (TRAZABILIDAD DE ESTADOS)
-- ============================================================================
-- Agregamos la columna ID_ESTADO al detalle para saber en qué estado quedó el neumático tras la acción
ALTER TABLE SPEED400AT.NEU_DETALLE ADD COLUMN ID_ESTADO INT;

-- Migración de datos históricos basada en la Acción
UPDATE SPEED400AT.NEU_DETALLE D
SET ID_ESTADO = (
    CASE 
        WHEN TIPO_ACCION IN ('INGRESO', 'INGRESO_INVENTARIO', 'DESMONTAJE', 'COMPRA') 
            THEN (SELECT ID_ESTADO FROM SPEED400AT.NEU_ESTADO WHERE CODIGO_INTERNO = 'DISPONIBLE')
        WHEN TIPO_ACCION IN ('MONTAJE', 'ROTACION', 'ASIGNACION') 
            THEN (SELECT ID_ESTADO FROM SPEED400AT.NEU_ESTADO WHERE CODIGO_INTERNO = 'ASIGNADO')
        WHEN TIPO_ACCION IN ('BAJA', 'BAJA DEFINITIVA') 
            THEN (SELECT ID_ESTADO FROM SPEED400AT.NEU_ESTADO WHERE CODIGO_INTERNO = 'BAJA')
        WHEN TIPO_ACCION IN ('RECUPERADO', 'RECUPERO') 
            THEN (SELECT ID_ESTADO FROM SPEED400AT.NEU_ESTADO WHERE CODIGO_INTERNO = 'RECUPERADO')
        ELSE 
            (SELECT ID_ESTADO FROM SPEED400AT.NEU_ESTADO WHERE CODIGO_INTERNO = 'DISPONIBLE') -- Default seguro
    END
);

-- 7. "Soft Drop" de columna antigua en Cabecera
-- Para efectos de esta limpieza, la conservaremos 1 minuto mientras refactorizamos, pero el objetivo es NO USARLA.
-- ALTER TABLE SPEED400AT.NEU_CABECERA DROP COLUMN ESTADO_ACTUAL; 
-- (La dejaremos para backup por ahora, el servicio dejará de leerla)
