-- MIGRACION 009: Estandarización de Acciones (Trazabilidad Homologada)
-- Autor: Antigravity AI
-- Fecha: 2025-12-09
-- Descripción: Crea Catálogo NEU_ACCION y normaliza el historial.

-- 1. Crear Tabla de Acciones (Con IDs fijos para reportes externos)
CREATE TABLE SPEED400AT.NEU_ACCION (
    ID_ACCION INT NOT NULL PRIMARY KEY, -- ID fijo (no identity) para consistencia total
    CODIGO_INTERNO VARCHAR(20) NOT NULL UNIQUE, 
    DESCRIPCION VARCHAR(50) NOT NULL
);

-- 2. Poblar Acciones Maestras (IDs Fijos Estándar)
INSERT INTO SPEED400AT.NEU_ACCION (ID_ACCION, CODIGO_INTERNO, DESCRIPCION) VALUES (1, 'INGRESO', 'INGRESO AL INVENTARIO');
INSERT INTO SPEED400AT.NEU_ACCION (ID_ACCION, CODIGO_INTERNO, DESCRIPCION) VALUES (2, 'MONTAJE', 'MONTAJE EN VEHICULO');
INSERT INTO SPEED400AT.NEU_ACCION (ID_ACCION, CODIGO_INTERNO, DESCRIPCION) VALUES (3, 'DESMONTAJE', 'DESMONTAJE DE VEHICULO');
INSERT INTO SPEED400AT.NEU_ACCION (ID_ACCION, CODIGO_INTERNO, DESCRIPCION) VALUES (4, 'ROTACION', 'ROTACION DE POSICION');
INSERT INTO SPEED400AT.NEU_ACCION (ID_ACCION, CODIGO_INTERNO, DESCRIPCION) VALUES (5, 'BAJA', 'BAJA DEFINITIVA');
INSERT INTO SPEED400AT.NEU_ACCION (ID_ACCION, CODIGO_INTERNO, DESCRIPCION) VALUES (6, 'RECUPERO', 'RECUPERACION DE NEUMATICO');
INSERT INTO SPEED400AT.NEU_ACCION (ID_ACCION, CODIGO_INTERNO, DESCRIPCION) VALUES (7, 'INSPECCION', 'INSPECCION RUTINARIA');
INSERT INTO SPEED400AT.NEU_ACCION (ID_ACCION, CODIGO_INTERNO, DESCRIPCION) VALUES (8, 'COMPRA', 'COMPRA DE NEUMATICO');

-- 3. Modificar Tabla Detalle
ALTER TABLE SPEED400AT.NEU_DETALLE ADD COLUMN ID_ACCION INT;

-- 4. Migrar Datos Históricos
-- Mapeo inteligente de strings variados a IDs estandarizados
UPDATE SPEED400AT.NEU_DETALLE D
SET ID_ACCION = (
  CASE 
    WHEN UPPER(TIPO_ACCION) LIKE '%INGRESO%' THEN (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'INGRESO')
    WHEN UPPER(TIPO_ACCION) LIKE '%COMPRA%' THEN (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'COMPRA')
    WHEN UPPER(TIPO_ACCION) LIKE '%MONTAJE%' AND UPPER(TIPO_ACCION) NOT LIKE '%DESMONTAJE%' THEN (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'MONTAJE')
    WHEN UPPER(TIPO_ACCION) LIKE '%DESMONTAJE%' THEN (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'DESMONTAJE')
    WHEN UPPER(TIPO_ACCION) LIKE '%ROTACION%' THEN (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'ROTACION')
    WHEN UPPER(TIPO_ACCION) LIKE '%BAJA%' THEN (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'BAJA')
    WHEN UPPER(TIPO_ACCION) LIKE '%RECUPERA%' OR UPPER(TIPO_ACCION) LIKE '%RECUPERO%' THEN (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'RECUPERO')
    WHEN UPPER(TIPO_ACCION) LIKE '%INSPECCION%' THEN (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'INSPECCION')
    ELSE (SELECT ID_ACCION FROM SPEED400AT.NEU_ACCION WHERE CODIGO_INTERNO = 'INGRESO') -- Default seguro
  END
);

-- 5. FK Constraint
ALTER TABLE SPEED400AT.NEU_DETALLE 
ADD CONSTRAINT FK_NEU_ACCION FOREIGN KEY (ID_ACCION) REFERENCES SPEED400AT.NEU_ACCION(ID_ACCION);
